### ISSUE TITLE
Error while running rtsplog_amd64 

### ISSUE THREAD

**Issue by barryhartman** [AlexxIT/rtsplog#1]
When I try to run the command rtsplog_amd64 I get the following error:

1.
E:\Download>**rtsplog_amd64 rtsp://user:pass@192.168.1.158:554/av_stream/ch0**
2022/08/23 16:19:07 RTSP/1.0 401 Unauthorized
CSeq: 1
WWW-Authenticate: Digest realm="Login to da9be08fea8a0bee6b819035606bebc7", nonce="4a96a2793ff5ed4b12968587e6f6becd"

2022/08/23 16:19:07 RTSP/1.0 404 Not Found
CSeq: 2

panic: read tcp 192.168.1.30:22401->192.168.1.158:554: wsarecv: An existing connection was forcibly closed by the remote host.

goroutine 1 [running]:
main.main()
        rtsplog/main.go:38 +0x1b7

However I think the rtsp stream should be called with the following command(at least that's how I use it):

2.
E:\Download>**rtsplog_amd64 rtsp://user:pass@192.168.1.158/cam/realmonitor?channel=1&subtype=0&proto=Onvif**
2022/08/23 16:17:39 RTSP/1.0 401 Unauthorized
CSeq: 1
WWW-Authenticate: Digest realm="Login to da9be08fea8a0bee6b819035606bebc7", nonce="6b16ff9208678e83fcca0978e6df43af"

2022/08/23 16:17:39 RTSP/1.0 200 OK
CSeq: 2
Public: OPTIONS, DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, TEARDOWN, SET_PARAMETER, GET_PARAMETER
Server: Rtsp Server/3.0

2022/08/23 16:17:39 RTSP/1.0 404 Not Found
CSeq: 3
WWW-Authenticate: Digest realm="Login to da9be08fea8a0bee6b819035606bebc7", nonce="6b16ff9208678e83fcca0978e6df43af"

panic: bad status code: 404 (Not Found)

goroutine 1 [running]:
main.main()
        rtsplog/main.go:38 +0x1b7
'subtype' is not recognized as an internal or external command,
operable program or batch file.
'proto' is not recognized as an internal or external command,
operable program or batch file.

But it raises also an error

**Comment by AlexxIT** [comment]
Use https://github.com/AlexxIT/go2rtc
And enable logs in `go2rtc.yaml`
```yaml
log:
  rtsp: trace
```

It will do the same thing
